dubbo:
  application:
    name: dubbo-goods-service
  registry:
    address: zookeeper://47.111.68.145:2181
    timeout: 10000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.czy.goods.service